static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO

                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/api/v1/auth/" }
                          route: { cluster: auth_service }

                        - match: { prefix: "/api/v1/users/" }
                          route: { cluster: auth_service }

                        - match: { prefix: "/api/v1/accounts/" }
                          route: { cluster: auth_service }

                        - match: { prefix: "/api/v1/orders/" }
                          route: { cluster: order_service }

                http_filters:
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication

                      providers:
                        auth_provider:
                          issuer: "http://auth-service.default.svc.cluster.local"
                          remote_jwks:
                            http_uri:
                              uri: "http://auth-service.default.svc.cluster.local/.well-known/jwks.json"
                              cluster: jwks_cluster
                              timeout: { seconds: 5 }
                            cache_duration: { seconds: 600 }

                      rules:
                        # PUBLIC → no JWT required
                        - match: { prefix: "/api/v1/auth/" }
                          requires:
                            allow_missing: {}

                        # PROTECTED → must have JWT
                        - match: { prefix: "/api/v1/users/" }
                          requires:
                            provider_name: "auth_provider"

                        - match: { prefix: "/api/v1/accounts/" }
                          requires:
                            provider_name: "auth_provider"

                        - match: { prefix: "/api/v1/orders/" }
                          requires:
                            provider_name: "auth_provider"

                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: auth_service
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: auth_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: auth-service.default.svc.cluster.local
                      port_value: 8081

    - name: order_service
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: order_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: order-service.default.svc.cluster.local
                      port_value: 8082

    - name: jwks_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: jwks_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: auth-service.default.svc.cluster.local
                      port_value: 8081

admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
