apiVersion: configuration.konghq.com/v1
kind: KongService
metadata:
  name: order-service
  namespace: default
spec:
  url: http://order-service.default.svc.cluster.local:8082
---
apiVersion: configuration.konghq.com/v1
kind: KongRoute
metadata:
  name: order-route
  namespace: default
  annotations:
    konghq.com/plugins: jwt-verify-plugin
spec:
  paths:
    - /api/v1/orders
  strip_path: false
  service:
    name: order-service
