apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-verify-plugin
  namespace: default
plugin: jwt
config:
  run_on_preflight: true
  secret_is_base64: false
  claims_to_verify: []
  key_claim_name: kid
  jwks_uri: "http://api.jwtauth.nani.id.vn/.well-known/jwks.json"
